name: debt-locker
version: 2.0.0-beta.0
source: contracts
packages:
  - path: contracts/DebtLocker.sol
    contractName: DebtLocker
  - path: contracts/DebtLockerInitializer.sol
    contractName: DebtLockerInitializer
  - path: contracts/DebtLockerFactory.sol
    contractName: DebtLockerFactory
customDescription: Maple Debt Locker Artifacts and ABIs
