name: debt-locker
version: 1.1.0
source: contracts
packages:
  - path: contracts/DebtLockerFactory.sol
    contractName: DebtLockerFactory
    customChecksum:
  - path: contracts/DebtLocker.sol
    contractName: DebtLocker
    customChecksum:
customDescription: Debt Locker Artifacts and ABIs
