name: debt-locker
version: 2.0.0
source: contracts
packages:
  - path: contracts/DebtLocker.sol
    contractName: DebtLocker
    customChecksum: 0x852d096582581e400aa000467ea9e59e7939c20e4cbbfe0c0f3d04ac4286f600
  - path: contracts/DebtLockerFactory.sol
    contractName: DebtLockerFactory
    customChecksum: 0x90aa9362f8cf6d72464bb112ecddba515337250c33bff5c86e55831f005776d3
  - path: contracts/DebtLockerInitializer.sol
    contractName: DebtLockerInitializer
    customChecksum: 0xc47b9628c0eaa75890eaced74c259ae3613b4cb0f5090a2925c2fae166f59486
customDescription: Maple Debt Locker Artifacts and ABIs
