version: 2.1

jobs:
  dapp_build:
    docker:
      - image: bakii0499/dapptools:0.46.0
    steps:
      - run:
          name: Checkout debt-locker
          command: |
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:maple-labs/debt-locker.git .
            git checkout $CIRCLE_BRANCH

workflows:
  version: 2
  test_all:
    jobs:
      - dapp_build:
          context: seth
