name: pool-v2
version: 1.0.0-alpha.0
source: contracts
packages:
  - path: contracts/proxy/LoanManagerFactory.sol
    contractName: LoanManagerFactory
  - path: contracts/proxy/LoanManagerInitializer.sol
    contractName: LoanManagerInitializer
  - path: contracts/proxy/LoanManagerStorage.sol
    contractName: LoanManagerStorage
  - path: contracts/proxy/PoolManagerFactory.sol
    contractName: PoolManagerFactory
  - path: contracts/proxy/PoolManagerInitializer.sol
    contractName: PoolManagerInitializer
  - path: contracts/proxy/PoolManagerStorage.sol
    contractName: PoolManagerStorage
  - path: contracts/LoanManager.sol
    contractName: LoanManager
  - path: contracts/Pool.sol
    contractName: Pool
  - path: contracts/PoolDelegateCover.sol
    contractName: PoolDelegateCover
  - path: contracts/PoolDeployer.sol
    contractName: PoolDeployer
  - path: contracts/PoolManager.sol
    contractName: PoolManager
  - path: contracts/TransitionLoanManager.sol
    contractName: TransitionLoanManager
customDescription: Pool V2 Artifacts and ABIs
