name: debt-locker
version: 4.0.0-alpha.0
source: contracts
packages:
  - path: contracts/DebtLocker.sol
    contractName: DebtLocker
  - path: contracts/DebtLockerFactory.sol
    contractName: DebtLockerFactory
  - path: contracts/DebtLockerInitializer.sol
    contractName: DebtLockerInitializer
customDescription: Maple Debt Locker Artifacts and ABIs
