name: Forge Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Checkout liquidations private submodule
        env:
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
        shell: bash
        run: |
          mkdir $HOME/.ssh
          echo "$SSH_KEY_LIQUIDATIONS" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          git submodule update --init --recursive modules/liquidations

      - name: Checkout loan private submodule
        env:
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
        shell: bash
        run: |
          echo "$SSH_KEY_LOAN" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          git submodule update --init --recursive modules/loan

      - name: Checkout public submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        run: ./scripts/test.sh -p super_deep
